name: Build Workflow

on: [push]

jobs:
  build-test:
    name: Build & Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Use Node 16
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "16"
          cache: "npm"

      - name: Install NPM dependencies
        run: npm install

      - name: Check formatting
        run: npm run format-check

      - name: Compile contracts
        run: npm run compile

      - name: Run tests
        run: npm run test
